fname = input("Enter first name: ")
lname = input("Enter last name: ")
mname = input("Enter middle name: ")
bday = input("Enter birthday: ")
gender = input("Enter gender (M/F): ")
address = input("Enter address: ")
course = input("Enter course: ")
year_level = input("Enter year level: ")

print("====================================================")
print("First name: ", fname)
print("Last name: ", lname)
print("Middle name: ", mname)
print("Birthday: ", bday)
print("Gender: ", gender)
print("Address: ", address)
print("Course: ", course)
print("Year level: ", year_level)